version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_tkpm
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - mysql
networks:
  external_network:
    external: true
